name: ServerCore
main: ServerCore\ServerCore
version: 1.1
api: 3.0.0, 4.0.0
load:
author: IceCruelStuff
description: A plugin to heal players
website: https://github.com/IceCruelStuff/ServerCore
commands:
  heal:
    description: Heal yourself
permissions:
  Mod:
    default: op
    description: Allows player to use /heal
    children:
